server:
  port: 8080
servlet:
  encoding:
    force-response: true
# S3 설정
#  multipart:
#    enabled: true
#    max-file-size: 20MB
#    max-request-size: 20MB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# S3 설정
#  profiles:
#    include:
#      - aws
#      - credentials
jwt:
  token:
    secret: secret.aa.bb.cc